# Generated by Django 3.2.4 on 2021-08-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('auteur', models.CharField(default='John Doe', max_length=100)),
                ('maison_edition', models.CharField(max_length=150)),
                ('pages', models.IntegerField()),
                ('prix', models.IntegerField()),
                ('quante', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.BooleanField()),
                ('date_parution', models.DateField()),
            ],
            options={
                'ordering': ['-date_parution'],
            },
        ),
    ]
