# Generated by Django 3.2.4 on 2021-08-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_quante_livre_quantite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='maison_edition',
        ),
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.CharField(default='Sawadogo Omar', max_length=100),
        ),
    ]
