# Generated by Django 3.2.4 on 2021-08-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_livre_date_parution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ens', models.CharField(max_length=100)),
                ('filiere', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=100)),
                ('matiere', models.CharField(max_length=100)),
                ('vh', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Livre',
        ),
    ]
