# Generated by Django 3.2.4 on 2021-08-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210815_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=50)),
                ('annee_publication', models.CharField(max_length=10)),
                ('pages', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cours',
        ),
    ]
